services:
  postgres:
    image: postgres:17-alpine
    container_name: smartflow-app-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartflow
    volumes:
      - smartflow_pgdata:/var/lib/postgresql/data

volumes:
  smartflow_pgdata:
